### PR TITLE
Update ezgoogleanalytics.php

### PR DESCRIPTION
**Pull request by Dove28**
Dove le meilleur des Devs qui t'aime bien même quand tu mets deux default dans un switch!

### CODE REVIEW

**Review by pcoipeault — APPROVED** [review]

**Review by xl714 — APPROVED** [review]

**Review by lendormi — COMMENTED** [review]
Please change your commit message and write in english. Don't be so arrogant 👍 . This project is opensourced

**Comment by Dove28** [comment]
My name is Dove and i'm the best of web developper alive!
I always like you even if you put two default in a switch.

**Comment by pcoipeault** [comment]
So no code update to fix the issue ?

**Comment by lendormi** [comment]
the commit message is not right. I prefer closing this PR rather than letting it open

**Pull request closed without merging**
